# Generated by Django 3.2.3 on 2021-05-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('event', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('No_of_participants', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
