# Generated by Django 3.2.3 on 2021-05-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_eventdata2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventData2',
        ),
    ]
