# Generated by Django 3.2.3 on 2021-05-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('homepage', '0006_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('event_name', models.CharField(max_length=300)),
                ('Team_Name', models.CharField(max_length=30)),
                ('no_of_participants', models.IntegerField()),
                ('College_Email_ID', models.EmailField(max_length=30)),
                ('Mob_No', models.BigIntegerField()),
            ],
        ),
    ]
